---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.qq.com:465'
      smtp_from: '1525996190@qq.com'
      smtp_auth_username: '1525996190@qq.com'
      smtp_auth_password: 'gszcljszrjnihbed'
      smtp_require_tls: false

    route:
      group_by: [ 'alertname' ]
      receiver: 'webhook'

    receivers:
      - name: 'default-receiver'
        email_configs:
          - to: 'yushanshan@sensorsdata.com'
            send_resolved: true
      - name: 'webhook'
        webhook_configs:
          - url: 'http://prometheus-alert.monitoring.svc:8080/prometheusalert?type=wx&tpl=prometheus-wx'
            send_resolved: true

