---
# handlers file for init_linux

- name: reload sysctl
  command: sysctl -p

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart ntp
  service:
    name: ntpd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
