---
global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '1525996190@qq.com'
  smtp_auth_username: '1525996190@qq.com'
  smtp_auth_password: 'gszcljszrjnihbed'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  email_configs:
    - to: 'yushanshan@sensorsdata.com'
      send_resolved: true