apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host
  namespace: yss
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'

