apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host   # pv属于集群资源，不需要设置namespace，设置了也不起效果
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'

