apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-pvc
  namespace: yss
spec:
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: nfs-pvc1
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sleep","3600"]
      volumeMounts:
        - name: data-vol
          mountPath: /opt









