---
apiVersion: v1
kind: ReplicationController
# metadata 里面写标签
metadata:
  name: rc-demo
  labels:
    app: rc   #这个是 rc 的标签，不是 pod 的标签
spec:
  # spec 里面有 replicas  selector  template(最主要的)
  replicas: 1
  # selector 写标签
  selector:
    app: rc
  template:
    # template 里面的 metadata 写标签
    metadata:
      labels:
        app: rc

    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
          - containerPort: 81





