apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-disk-pvc
  namespace: yss
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi