apiVersion: v1
kind: Pod
metadata:
  name: pod-probe-liveness
  namespace: yss
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      livenessProbe:  #存活性探针，没有 /tmp/hello.txt，pod会被频繁重启
        exec:
          command: ["/bin/cat","/tmp/hello.txt"]


