---
apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  namespace: yss
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent

  initContainers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c","ping -c 3 baidu.com &&echo init container exec success"]

