apiVersion: v1
kind: Pod
metadata:
  name: restart-policy-pod
  namespace: yss
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-port
          containerPort: 80
      livenessProbe:
        httpGet:  #通过tcpSocket的livenessprobe检测pod是否可用
          port: 80
          path: /hello  #让pod失败，然后设置重启策略为never
          scheme: HTTP  #默认是http
        initialDelaySeconds: 30
        timeoutSeconds: 5
  restartPolicy: Never


