apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: yss
  name: pod-reader
rules:
  - apiGroups: [""]  #空字符串，表示核心api群
    resources: ["pods"]
    verbs: ["get","watch","list"]




