apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-required
  namespace: yss
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: env
                operator: NotIn
                values: ['test']
          topologyKey: kubernetes.io/hostname


  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent


