---
route:
  group_by: ['alertname']
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://dummy-webhook:8080'  # 替换为真实Webhook或邮件配置
    send_resolved: true