global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # 指向Alertmanager

rule_files:
  - '/etc/prometheus/alert_rules.yml'  # 告警规则路径

remote_write:
  - url: http://thanos-receiver:10903/api/v1/receive  # 远程写入到Thanos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']