---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs1
spec:
  replicas: 1
  selector:
    matchLabels:  # label selector,必须匹配pod模板中的标签
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 81





