---
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  namespace: yss
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  nodeSelector:
    env: prod