---
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  namespace: yss
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:  #硬限制
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values: ["dev","prod"]
