apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  namespace: yss
spec:
  volumes:
    - name: nfs-vol
      nfs:
        server: 123.56.222.255
        path: /data/nfs_dir

  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nfs-vol
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /log
          name: nfs-vol
      command: [ "/bin/sh","-c","tail -f /log/access.log" ]

