apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dep
  namespace: yss
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat  # 容器的名字就叫tomcat
          image: tomcat
          ports:
            - containerPort: 8080  # tomcat默认端口8080
