---
# 创建一个pod，挂在configmap

apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  namespace: yss
spec:
  volumes:
    - name: data-vol
      configMap:
        name: configmap-demo
  containers:
    - name: busybox
      image: busybox
      command: ["sleep","3600"]
      volumeMounts:
        - name: data-vol
          mountPath: /opt
