---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: yss
spec:
  volumes:
    - name: data-vol
      secret:
        secretName: secret-demo
  containers:
    - name: busybox
      image: busybox
      command: ["sleep","3600"]
      volumeMounts:
        - name: data-vol
          mountPath: /opt
