apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-svc
  namespace: yss
spec:
  clusterIP: None  # 表示 headless service
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 8070
      targetPort: 80
      protocol: TCP
