apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: yss
spec:
  selector:
    app: nginx
  type: NodePort # 暴露给外网
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 30001  #NodePort模式
  sessionAffinity: ClientIP

