apiVersion: v1
kind: Service
metadata:
  name: nginx-limit-svc
  namespace: yss
spec:
  type: NodePort
  selector:
    app: nginx-limit
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
      nodePort: 30004
