apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx-svc
  namespace: yss
spec:
  type: NodePort
  clusterIP: 10.96.0.2 #指定clusterip，也可以不指定
  selector:
    app: nginx
  ports:
    - port: 8060  # 集群内部访问的端口
      nodePort: 30002  #集群外部访问的端口
      targetPort: 80  #容器端口
      protocol: TCP
