---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: yss
spec:
  selector:
    app: tomcat
  type: ClusterIP
  ports:
    - port: 8080  # service 端口
      targetPort: 8080
  sessionAffinity: None