apiVersion: rbac.authorization.k8s.io
kind: ClusterRoleBinding
metadata:
  name: secret-reader-cluster-role-binding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader


