apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-role-binding
  namespace: yss
subjects:
  - kind: User
    name: xiaoyumi
    apiGroup: rbac.authorization.k8s.io  #用户和组没有名称空间
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader





