apiVersion: rbac.authorization.k8s.io
kind: RoleBinding
metadata:
  name: secret-reader-role-binding
  namespace: yss
subject:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: xiaoyumi


roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader

